import { MyFormData } from "@components/app/forms/formWrapper/types"

export const filterFormData: MyFormData = {
  fields: {
    provider_name: {
      label: "Хостинг",
      value: "",
      valueObj: { value: "", label: "Не выбрано" },
      valueArr: [],
      type: "text",
      dropdown: "default",
      options: [],
      validations: {},
      errorMessage: "",
      dirty: false,
    },
    provider_id: {
      label: "Хостинг",
      type: "select",
      value: "",
      valueObj: { value: "", label: "Не выбрано" },
      valueArr: [],
      dropdown: "default",
      options: [{ value: "", label: "Не выбрано" }],
      validations: {},
      errorMessage: "",
      dirty: false,
    },
    registrator_id: {
      label: "Аккаунт хостинга",
      type: "select",
      value: "",
      valueObj: { value: "", label: "Не выбрано" },
      valueArr: [],
      dropdown: "default",
      options: [{ value: "", label: "Не выбрано" }],
      validations: {},
      dependency: {
        field: "provider_id",
        type: "loadOptions",
      },
      errorMessage: "",
      dirty: false,
    },
    department_name: {
      label: "Отдел",
      value: "",
      valueObj: { value: "", label: "Не выбрано" },
      valueArr: [],
      dropdown: "default",
      options: [{ value: "", label: "Не выбрано" }],
      type: "select",
      validations: {},
      errorMessage: "",
      dirty: false,
    },
    active: {
      label: "Состояние",
      value: "",
      valueObj: { value: "", label: "Не выбрано" },
      valueArr: [],
      type: "select",
      dropdown: "default",
      options: [
        { value: "", label: "Не выбрано" },
        { value: "0", label: "Неактивно" },
        { value: "1", label: "Активно" },
      ],
      validations: {},
      errorMessage: "",
      dirty: false,
    },
  },
}
