cache:
  paths:
    - node_modules/

stages:
  - pre-production
  - production
before_script:
  - node -v
  - yarn -v
Build React APP Dev-release:
  stage: pre-production
  script:
    - yarn
    - yarn build
    - echo "Deploying to development server"
    - cp -r build/ /var/www
    - echo "Finished copying the build files"
  tags:
    - dev-shell
  only:
    - dev

Build React APP Prod-release:
  stage: production
  script:
    - yarn install
    - yarn build
    - echo "Deploying to production server"
    - cp -r build/ /var/www
    - echo "Finished copying the build files"
  tags:
    - prod-shell
  only:
    - main