import { MyFormData } from "@components/app/forms/formWrapper/types"

export const filterFormData: MyFormData = {
  fields: {
    available_condition: {
      label: "Код ответа",
      value: "",
      valueObj: { value: "", label: "Не выбрано" },
      valueArr: [],
      type: "select",
      dropdown: "default",
      options: [
        { value: "", label: "Не выбрано" },
        { value: "available", label: "Доступен" },
        { value: "unavailable", label: "Недоступен" },
      ],
      validations: {},
      errorMessage: "",
      dirty: false,
    },
    active: {
      label: "Состояние",
      value: "",
      valueObj: { value: "", label: "Не выбрано" },
      valueArr: [],
      type: "select",
      dropdown: "default",
      options: [
        { value: "", label: "Не выбрано" },
        { value: "0", label: "Неактивен" },
        { value: "1", label: "Активен" },
      ],
      validations: {},
      errorMessage: "",
      dirty: false,
    },
    is_activated: {
      label: "Мониторинг",
      value: "",
      valueObj: { value: "", label: "Не выбрано" },
      valueArr: [],
      type: "select",
      dropdown: "default",
      options: [
        { value: "", label: "Не выбрано" },
        { value: "0", label: "Неактивен" },
        { value: "1", label: "Активен" },
      ],
      validations: {},
      errorMessage: "",
      dirty: false,
    },
    server_id: {
      label: "Сервер",
      value: "",
      valueObj: { value: "", label: "Не выбрано" },
      valueArr: [],
      type: "select",
      dropdown: "default",
      options: [{ value: "", label: "Не выбрано" }],
      validations: {},
      errorMessage: "",
      dirty: false,
    },
    provider_id: {
      label: "DNS-хостинг",
      value: "",
      valueObj: { value: "", label: "Не выбрано" },
      valueArr: [],
      type: "select",
      dropdown: "default",
      options: [{ value: "", label: "Не выбрано" }],
      validations: {},
      errorMessage: "",
      dirty: false,
    },
    registrator_id: {
      label: "Регистратор",
      type: "select",
      value: "",
      valueObj: { value: "", label: "Не выбрано" },
      valueArr: [],
      dropdown: "default",
      options: [{ value: "", label: "Не выбрано" }],
      validations: {},
      errorMessage: "",
      dirty: false,
    },
    department_name: {
      label: "Отдел",
      type: "select",
      value: "",
      valueObj: { value: "", label: "Не выбрано" },
      valueArr: [],
      dropdown: "default",
      options: [{ value: "", label: "Не выбрано" }],
      validations: {},
      errorMessage: "",
      dirty: false,
    },
    registration_date: {
      label: "Дата регистрации",
      value: "",
      valueObj: { value: "", label: "Не выбрано" },
      valueArr: [],
      dropdown: "default",
      options: [{ value: "", label: "Не выбрано" }],
      type: "text",
      validations: {},
      errorMessage: "",
      dirty: false,
    },
    expirationtime_condition: {
      label: "Дата окончания",
      value: "",
      valueObj: { value: "", label: "Не выбрано" },
      valueArr: [],
      dropdown: "default",
      options: [{ value: "", label: "Не выбрано" }],
      type: "text",
      validations: {},
      errorMessage: "",
      dirty: false,
    },
  },
}
